# Generated by Django 4.1.5 on 2023-02-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
